"""Pin reusable versions of external tools used by the project."""

VERSION_ACTIONLINT = "1.7.12"
VERSION_ACTIONLINT_PY = "1.7.12.24"
VERSION_GITLEAKS = "8.30.1"
VERSION_LIGHTHOUSE_CI = "0.15.1"
VERSION_PLAYWRIGHT = "1.61.1"
VERSION_REPOMIX = "1.16.1"
VERSION_RULESYNC = "14.0.1"
VERSION_SEMGREP = "1.169.0"
VERSION_SERENA = "1.6.0"
VERSION_SQLFLUFF = "4.2.2"
SHA_SERENA = "93b9544ea9def8e93cb6a90f8ea67befe3c8fee4"
FUENTE_SERENA = f"git+https://github.com/oraios/serena.git@{SHA_SERENA}"

ESPECIFICACION_SEMGREP_MISE = f"pipx:semgrep@{VERSION_SEMGREP}"
ESPECIFICACION_GITLEAKS_MISE = f"aqua:gitleaks/gitleaks@{VERSION_GITLEAKS}"
ESPECIFICACION_LIGHTHOUSE_MISE = f"npm:@lhci/cli@{VERSION_LIGHTHOUSE_CI}"
ESPECIFICACION_PLAYWRIGHT_MISE = f"npm:playwright@{VERSION_PLAYWRIGHT}"
ESPECIFICACION_REPOMIX_MISE = f"npm:repomix@{VERSION_REPOMIX}"
ESPECIFICACION_RULESYNC_MISE = f"npm:rulesync@{VERSION_RULESYNC}"
ESPECIFICACION_SQLFLUFF_MISE = f"pipx:sqlfluff@{VERSION_SQLFLUFF}"

__all__ = [
    "VERSION_ACTIONLINT",
    "VERSION_ACTIONLINT_PY",
    "VERSION_GITLEAKS",
    "VERSION_LIGHTHOUSE_CI",
    "VERSION_PLAYWRIGHT",
    "VERSION_REPOMIX",
    "VERSION_RULESYNC",
    "VERSION_SEMGREP",
    "VERSION_SERENA",
    "VERSION_SQLFLUFF",
    "SHA_SERENA",
    "FUENTE_SERENA",
    "ESPECIFICACION_SEMGREP_MISE",
    "ESPECIFICACION_GITLEAKS_MISE",
    "ESPECIFICACION_LIGHTHOUSE_MISE",
    "ESPECIFICACION_PLAYWRIGHT_MISE",
    "ESPECIFICACION_REPOMIX_MISE",
    "ESPECIFICACION_RULESYNC_MISE",
    "ESPECIFICACION_SQLFLUFF_MISE",
]
