"""Contracts for reproducible security and UX gates generated by Tramalia."""

from __future__ import annotations

import shutil
import subprocess
import tomllib
from pathlib import Path

import pytest

from tramalia.core.errores import ErrorEntradaInsegura
from tramalia.core.installer import options_for
from tramalia.core.integraciones import REGISTRO
from tramalia.core.scaffold import build_mise_toml
from tramalia.core.versiones_herramientas import (
    ESPECIFICACION_GITLEAKS_MISE,
    ESPECIFICACION_LIGHTHOUSE_MISE,
    ESPECIFICACION_PLAYWRIGHT_MISE,
    ESPECIFICACION_REPOMIX_MISE,
    ESPECIFICACION_RULESYNC_MISE,
    ESPECIFICACION_SEMGREP_MISE,
    ESPECIFICACION_SQLFLUFF_MISE,
    VERSION_GITLEAKS,
    VERSION_LIGHTHOUSE_CI,
    VERSION_PLAYWRIGHT,
    VERSION_REPOMIX,
    VERSION_RULESYNC,
    VERSION_SEMGREP,
    VERSION_SQLFLUFF,
)


def _herramienta(clave: str):
    return next(herramienta for herramienta in REGISTRO if herramienta.clave == clave)


def _inventario_bytes(raiz: Path) -> dict[str, bytes]:
    return {
        ruta.relative_to(raiz).as_posix(): ruta.read_bytes()
        for ruta in sorted(raiz.rglob("*"))
        if ruta.is_file()
    }


def test_seguridad_generada_fija_versiones_y_usa_gitleaks_git() -> None:
    contenido = build_mise_toml({"stacks": ["python"], "features": ["security"]})

    assert f'"pipx:semgrep" = "{VERSION_SEMGREP}"' in contenido
    assert f'"aqua:gitleaks/gitleaks" = "{VERSION_GITLEAKS}"' in contenido
    assert "gitleaks git --redact --no-banner" in contenido
    assert "gitleaks dir . --redact --no-banner --max-target-megabytes 10" in contenido
    assert (
        "semgrep scan --config .tramalia/configuracion/semgrep/seguridad-python.yml "
        "--error --metrics=off --disable-version-check"
    ) in contenido
    assert "gitleaks detect" not in contenido
    assert '"latest"' not in contenido


def test_seguridad_generada_conserva_orden_fail_closed() -> None:
    contenido = build_mise_toml({"stacks": ["python"], "features": ["security"]})
    comandos = tomllib.loads(contenido)["tasks"]["security"]["run"]

    assert comandos == [
        "gitleaks git --redact --no-banner",
        "gitleaks dir . --redact --no-banner --max-target-megabytes 10",
        (
            "semgrep scan --config .tramalia/configuracion/semgrep/seguridad-python.yml "
            "--error --metrics=off --disable-version-check"
        ),
    ]


def test_ux_generada_fija_lighthouse_y_playwright_sin_instalar() -> None:
    contenido = build_mise_toml({"stacks": ["react"], "features": ["ux"]})
    comandos = tomllib.loads(contenido)["tasks"]["ux"]["run"]

    assert f'"npm:@lhci/cli" = "{VERSION_LIGHTHOUSE_CI}"' in contenido
    assert f'"npm:playwright" = "{VERSION_PLAYWRIGHT}"' in contenido
    assert comandos == ["lhci autorun", "playwright test"]
    assert " install " not in f" {contenido.lower()} "
    assert '"latest"' not in contenido


def test_mise_generado_no_emite_versiones_flotantes_en_capacidades() -> None:
    contenido = build_mise_toml(
        {
            "stacks": ["python", "react", "postgres"],
            "features": ["context", "security", "database", "sync", "ux"],
        }
    )

    assert f'"npm:repomix" = "{VERSION_REPOMIX}"' in contenido
    assert f'"pipx:sqlfluff" = "{VERSION_SQLFLUFF}"' in contenido
    assert f'"npm:rulesync" = "{VERSION_RULESYNC}"' in contenido
    assert '"latest"' not in contenido


def test_registro_instalador_y_scaffold_comparten_especificaciones() -> None:
    esperadas = {
        "repomix": f"mise use {ESPECIFICACION_REPOMIX_MISE}",
        "semgrep": f"mise use {ESPECIFICACION_SEMGREP_MISE}",
        "gitleaks": f"mise use {ESPECIFICACION_GITLEAKS_MISE}",
        "sqlfluff": f"mise use {ESPECIFICACION_SQLFLUFF_MISE}",
        "rulesync": f"mise use {ESPECIFICACION_RULESYNC_MISE}",
        "lhci": f"mise use {ESPECIFICACION_LIGHTHOUSE_MISE}",
        "playwright": f"mise use {ESPECIFICACION_PLAYWRIGHT_MISE}",
    }

    for clave, sugerencia in esperadas.items():
        herramienta = _herramienta(clave)
        assert herramienta.sugerencia_instalacion == sugerencia
        assert options_for(herramienta)[0].args == (
            "mise",
            "use",
            sugerencia.removeprefix("mise use "),
        )

    opcion_semgrep = next(
        opcion for opcion in options_for(_herramienta("semgrep")) if opcion.method == "uv"
    )
    assert opcion_semgrep.args == ("uv", "tool", "install", f"semgrep=={VERSION_SEMGREP}")
    opcion_lighthouse = next(
        opcion for opcion in options_for(_herramienta("lhci")) if opcion.method == "npm"
    )
    assert opcion_lighthouse.args == (
        "npm",
        "install",
        "-g",
        f"@lhci/cli@{VERSION_LIGHTHOUSE_CI}",
    )


def test_generador_real_es_confinado_determinista_y_empaqueta_semgrep(tmp_path: Path) -> None:
    from scripts.generar_proyecto_prueba_seguridad import generar_proyecto

    primera = generar_proyecto(tmp_path, Path("primera"))
    segunda = generar_proyecto(tmp_path, Path("segunda"))

    assert primera == (tmp_path / "primera").resolve()
    assert segunda == (tmp_path / "segunda").resolve()
    assert _inventario_bytes(primera) == _inventario_bytes(segunda)
    configuracion_generada = (
        primera / ".tramalia" / "configuracion" / "semgrep" / "seguridad-python.yml"
    )
    configuracion_auditada = (
        Path(__file__).resolve().parents[2] / "configuracion" / "semgrep" / "seguridad-python.yml"
    )
    assert configuracion_generada.read_bytes() == configuracion_auditada.read_bytes()
    assert '"latest"' not in (primera / "mise.toml").read_text(encoding="utf-8")


def test_generador_rechaza_escape_y_destino_con_contenido(tmp_path: Path) -> None:
    from scripts.generar_proyecto_prueba_seguridad import generar_proyecto

    raiz = tmp_path / "raiz"
    raiz.mkdir()
    with pytest.raises(ErrorEntradaInsegura):
        generar_proyecto(raiz, Path("../fuera"))
    assert not (tmp_path / "fuera").exists()

    ocupada = raiz / "ocupada"
    ocupada.mkdir()
    (ocupada / "usuario.txt").write_text("conservar", encoding="utf-8")
    with pytest.raises(ErrorEntradaInsegura):
        generar_proyecto(raiz, Path("ocupada"))
    assert (ocupada / "usuario.txt").read_text(encoding="utf-8") == "conservar"


@pytest.mark.integracion
def test_backend_mise_resuelve_gitleaks_fijado() -> None:
    ejecutable = shutil.which("mise")
    if ejecutable is None:
        pytest.skip("mise no esta instalado; no se simula la resolucion del backend")

    disponibles = subprocess.run(
        [ejecutable, "ls-remote", "aqua:gitleaks/gitleaks"],
        check=True,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert VERSION_GITLEAKS in disponibles.stdout.split()
    simulacion = subprocess.run(
        [ejecutable, "use", "--dry-run", ESPECIFICACION_GITLEAKS_MISE],
        check=False,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert simulacion.returncode == 0, simulacion.stdout + simulacion.stderr
